import json

class ClinicalLLMReasoningEngine:
    """
    Multimodal Reasoning & Explanation Synthesis Layer.
    Combines CV predictions, Clinical ML risk, and RAG medical evidence into source-grounded clinical reports.
    """
    def synthesize_report(
        self,
        cv_result: dict,
        clinical_result: dict,
        rag_evidence: list,
        patient_info: dict = None
    ) -> dict:
        """
        Synthesizes structured clinical decision-support report.
        """
        patient_id = patient_info.get("patient_id", "PT-1001") if patient_info else "PT-1001"
        age = patient_info.get("age", 58) if patient_info else 58
        hba1c = patient_info.get("hba1c", 8.2) if patient_info else 8.2
        duration = patient_info.get("diabetes_duration_years", 12) if patient_info else 12

        cv_stage = cv_result.get("stage_name", "Moderate Non-Proliferative DR")
        cv_conf = cv_result.get("confidence_score", 91.5)
        lesions = cv_result.get("detected_lesions", [])

        ml_risk_name = clinical_result.get("risk_name", "Elevated Clinical Risk")
        ml_risk_score = clinical_result.get("risk_score_percent", 64.5)
        risk_drivers = clinical_result.get("risk_drivers", [])

        # Format retrieved RAG sources for grounded citations
        citations = []
        evidence_summary_lines = []
        for doc in rag_evidence:
            citations.append(f"[{doc['id']}] {doc['title']} ({doc['source']})")
            evidence_summary_lines.append(f"- **[{doc['id']}] {doc['title']}**: {doc['content']}")

        # Determine referral urgency
        stage_num = cv_result.get("stage_code_num", 2)
        if stage_num >= 4:
            referral_urgency = "URGENT (Specialist evaluation within 1-2 weeks)"
            action_plan = "Immediate referral to Retina Specialist for fluorescein angiography, optical coherence tomography (OCT), and potential anti-VEGF / PRP laser intervention."
        elif stage_num == 3:
            referral_urgency = "HIGH (Specialist evaluation within 2-4 weeks)"
            action_plan = "Prompt ophthalmology referral. Perform OCT to evaluate for macular edema. Optimize glycemic and blood pressure targets."
        elif stage_num == 2:
            referral_urgency = "MODERATE (Specialist evaluation within 2-3 months)"
            action_plan = "Schedule comprehensive dilated eye exam within 2-3 months. Intensify glycemic management (target HbA1c < 7.0%) and BP control."
        elif stage_num == 1:
            referral_urgency = "ROUTINE (Annual screening protocol)"
            action_plan = "Continue annual dilated eye examination. Reinforce lifestyle and glycemic adherence."
        else:
            referral_urgency = "ROUTINE (Screening every 12-24 months)"
            action_plan = "Maintain regular diabetes eye screening every 12 to 24 months per ADA recommendations."

        # Executive Clinical Narrative Generation
        narrative = f"""
### Executive Clinical Impression
Patient **{patient_id}** ({age} years old, {duration} yrs T2D, HbA1c {hba1c}%) was evaluated using the Multimodal Diabetic Retinopathy Screening System.
- **Computer Vision Assessment**: Classed as **{cv_stage}** with **{cv_conf}%** model confidence.
- **Clinical ML Risk Model**: Evaluated at **{ml_risk_name}** ({ml_risk_score}% cumulative risk score).
- **Referral Urgency**: **{referral_urgency}**.

### 1. Computer Vision & Lesion Analysis
The deep visual feature analysis identified the following retinal hallmarks:
"""
        for lesion in lesions:
            narrative += f"- {lesion}\n"

        narrative += f"""
### 2. Clinical Biomarker & Risk Factors
The tabular clinical risk pipeline highlighted the following key patient risk drivers:
"""
        for driver in risk_drivers:
            narrative += f"- {driver}\n"

        narrative += f"""
### 3. Source-Grounded Medical Evidence (RAG)
The following clinical practice guidelines and peer-reviewed literature support this case evaluation:
"""
        for line in evidence_summary_lines:
            narrative += f"{line}\n"

        narrative += f"""
### 4. Suggested Action Plan & Next Steps
{action_plan}

> **Clinical Disclaimer & Scope of Use**:
> This automated report is generated by an AI decision-support system designed solely to assist qualified healthcare professionals. It does not replace professional clinical judgement, formal diagnostic examination, or specialist consultation.
"""

        return {
            "executive_summary": f"Case {patient_id}: {cv_stage} ({cv_conf}% conf) | {ml_risk_name} ({ml_risk_score}%)",
            "referral_urgency": referral_urgency,
            "action_plan": action_plan,
            "full_narrative_markdown": narrative.strip(),
            "citations": citations
        }
