import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowRight, Clock3, FilePlus2, ImagePlus, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const statusTone: Record<string, string> = { pending: "bg-amber-100 text-amber-900 border-amber-200", complete: "bg-emerald-100 text-emerald-900 border-emerald-200", failed: "bg-rose-100 text-rose-900 border-rose-200" };

export default function Dashboard() {
  const { user } = useAuth();
  const { data: cases = [], isLoading } = trpc.screening.list.useQuery();
  return (
    <div className="mx-auto max-w-6xl"><section className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="technical-label text-primary">workspace / case queue</p><h1 className="mt-2 text-4xl font-bold tracking-[-0.055em] sm:text-5xl">Good to see you, {user?.name?.split(" ")[0] || "there"}.</h1><p className="mt-3 max-w-xl text-muted-foreground">Create a structured screening case, retain its image and context, and follow the evidence trail as pipeline outputs become available.</p></div><Link href="/app/new"><Button className="button-press h-11 rounded-xl px-5"><FilePlus2 className="mr-2 h-4 w-4" />New screening</Button></Link></section>
      <div className="mt-9 grid gap-4 md:grid-cols-3"><OverviewCard label="Total cases" value={isLoading ? "—" : String(cases.length)} note="Saved to your workspace" icon={ImagePlus} /><OverviewCard label="Awaiting analysis" value={isLoading ? "—" : String(cases.filter(item => item.visualPipelineStatus === "pending").length)} note="Model pipeline not complete" icon={Clock3} /><OverviewCard label="Review status" value="Protected" note="Manus OAuth access control" icon={ShieldCheck} /></div>
      <div className="mt-10 blueprint-card rounded-2xl"><div className="flex flex-col justify-between gap-3 border-b border-border p-5 sm:flex-row sm:items-center"><div><p className="technical-label text-primary">recent cases</p><h2 className="mt-1 text-xl font-bold tracking-tight">Screening queue</h2></div><span className="technical-label text-muted-foreground">newest first</span></div>{isLoading ? <div className="space-y-3 p-5">{[1, 2, 3].map(item => <Skeleton key={item} className="h-16 w-full" />)}</div> : cases.length === 0 ? <EmptyQueue /> : <div className="divide-y divide-border">{cases.map(item => <Link key={item.id} href={`/app/cases/${item.id}`} className="surface-hover flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-primary/20 bg-secondary text-primary"><Activity className="h-5 w-5" /></span><div><p className="font-semibold tracking-tight">{item.patientId}</p><p className="mt-1 font-mono text-[11px] text-muted-foreground">{item.caseCode} · {new Date(item.createdAt).toLocaleDateString()}</p></div></div><div className="flex items-center justify-between gap-3 sm:justify-end"><span className={`rounded-full border px-2.5 py-1 font-mono text-[10px] uppercase ${statusTone[item.visualPipelineStatus ?? "pending"]}`}>{item.visualPipelineStatus ?? "pending"}</span><ArrowRight className="h-4 w-4 text-muted-foreground" /></div></Link>)}</div>}</div>
    </div>
  );
}

function OverviewCard({ label, value, note, icon: Icon }: { label: string; value: string; note: string; icon: typeof Activity }) { return <div className="blueprint-card surface-hover rounded-2xl p-5"><div className="flex items-start justify-between"><p className="technical-label text-muted-foreground">{label}</p><Icon className="h-4 w-4 text-primary" /></div><p className="metric-value mt-5 text-4xl font-bold">{value}</p><p className="mt-2 text-xs text-muted-foreground">{note}</p></div>; }
function EmptyQueue() { return <div className="grid min-h-72 place-items-center p-8 text-center"><div><span className="mx-auto grid h-12 w-12 place-items-center rounded-full border border-primary/25 bg-secondary"><ImagePlus className="h-5 w-5 text-primary" /></span><h3 className="mt-4 text-lg font-semibold">Your screening queue is empty.</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-muted-foreground">Begin with a retinal image and structured patient data to create a protected case record.</p><Link href="/app/new"><Button variant="outline" className="button-press mt-5 border-primary/25">Create first case <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div></div>; }
